### ISSUE TITLE
[not an issue] - jtc a newly developed json cli tool

### ISSUE THREAD

**Issue by ldn-softdev** [lowescott/weblog#19]
Hi Scott,
I came across your article https://blog.scottlowe.org/2018/06/28/more-handy-cli-tools-json/
and wonder if you would be interested looking at my newly developed tool jtc: https://github.com/ldn-softdev/jtc
- it's not widely known yet, but it's nearly as versatile as jq (well, given one is a language and mine is a utility), also it's objectively faster, but the main claim here is that it offers a much easier/feasible way to achieve JSON manipulations queries than jq.
Yes, it's only my biased opinion, that why I wonder if you'd be interested looking into it?
Thanks anyways!

**Comment by scottslowe** [comment]
I'll give this a closer look; thanks! A cursory glance shows there's some really interesting functionality here that I know I would probably find personally useful.
